language: python
python:
  - "2.7.13"
install:
  - pip install -r requirements.txt  # install dependencies
  - python setup.py install       # install magnetar library
script:
  - python -m pytest -vvv
