# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - defaults
dependencies:
  - astropy==2.0.11
  - corner=2.0.1=py_1001
  - emcee=2.2.1=pyh24bf2e0_4
  - matplotlib=2.0.0=np111py27_3
  - numpy=1.11.2=py27_blas_openblas_202
  - pandas==0.23.4
  - python=2.7.13=1
  - scipy=0.18.1=np111py27_blas_openblas_201
  - wget==3.2

