# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - conda-forge
dependencies:
  - python=2.7.13
  - numpy=1.11.2
  - scipy=0.18.1
  - matplotlib=2.0.0
  - corner=2.0.1
  - emcee=2.2.1
  - pip:
    - astropy==2.0.11
    - twine==1.12.1
    - wget==3.2
